SAVE_BACKUPS_TO = '/root/backups'
TMP_FOLDER = '/root/backups/tmp'
TAR_BIN = '/usr/bin/tar'
BACKUPS_TO_SAVE_LOCAL = 7

[LOGGING]
LOGLEVEL = 'INFO'
LOG_TO_CONSOLE = true
LOG_TO_FILE = true
LOGFILE = '/var/log/ddmail_backup_taker.log'
LOG_TO_SYSLOG = true
SYSLOG_SERVER = '/dev/log'

[FOLDERS]
USE = true
FOLDERS_TO_BACKUP = '/var/mail /var/lib/rspamd/dkim/'

[MARIADB]
USE = true
MARIADBDUMP_BIN = '/usr/bin/mariadb-dump'
DATABASES = 'all'
ROOT_PASSWORD = 'change_me'

[GPG_ENCRYPTION]
USE = true
PUBKEY_FINGERPRINT = 'change_me'

[BACKUP_RECEIVER]
USE = true
URL = 'https://change_me:change_me/receive_backup'
PASSWORD = 'change_me'

